#!/usr/bin/python3
import urllib.parse
import urllib.request
import json
import getpass
import pprint

pp = pprint.PrettyPrinter(indent=2)

usr = input("Username: ")
passw = getpass.getpass()

vals = '{"username" : "' + usr + '", "password" : "' + passw + '" }'
params = vals.encode('utf_8')
headers = {'Content-type' : 'application/json', 'User-Agent' : 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)' }

req = urllib.request.Request("https://quality.hubwoo.com/rest/auth/latest/session", params, headers)
res = urllib.request.urlopen(req)

jsr = json.loads(res.read().decode('utf_8'))

SESS_ID = jsr['session']['value']
SESS_NA = jsr['session']['name']

headers = {'Content-type' : 'application/json', 'User-Agent' : 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)', 'cookie' : SESS_NA + '=' + SESS_ID }
req = urllib.request.Request("https://quality.hubwoo.com/rest/api/latest/issue/PP-29", headers = headers)
res = urllib.request.urlopen(req)

jsr = json.loads(res.read().decode('utf_8'))

pp.pprint(jsr)
